{
  "ID": "oval:cn.openanolis:def:20230669",
  "Version": "1",
  "Class": "patch",
  "Metadata": {
    "Title": "ANSA-2023:0669: python-django security update (Important)",
    "Affected": {
      "Family": "unix",
      "Platform": [
        "Anolis OS 23"
      ]
    },
    "References": [
      {
        "RefID": "ANSA-2023:0669",
        "RefURL": "https://anas.openanolis.cn/errata/detail/ANSA-2023:0669",
        "Source": "ANSA"
      }
    ],
    "Description": "Package updates are available for Anolis 23 that fix the following vulnerabilities:\n\nCVE-2023-36053:\nIn Django 3.2 before 3.2.20, 4 before 4.1.10, and 4.2 before 4.2.3, EmailValidator and URLValidator are subject to a potential ReDoS (regular expression denial of service) attack via a very large number of domain name labels of emails and URLs.\n\nCVE-2023-41164:\nIn Django 3.2 before 3.2.21, 4.1 before 4.1.11, and 4.2 before 4.2.5, django.utils.encoding.uri_to_iri() is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.\n\nCVE-2023-43665:\nIn Django 3.2 before 3.2.22, 4.1 before 4.1.12, and 4.2 before 4.2.6, the django.utils.text.Truncator chars() and words() methods (when used with html=True) are subject to a potential DoS (denial of service) attack via certain inputs with very long, potentially malformed HTML text. The chars() and words() methods are used to implement the truncatechars_html and truncatewords_html template filters, which are thus also vulnerable. NOTE: this issue exists because of an incomplete fix for CVE-2019-14232.\n\nCVE-2023-46695:\nAn issue was discovered in Django 3.2 before 3.2.23, 4.1 before 4.1.13, and 4.2 before 4.2.7. The NFKC normalization is slow on Windows. As a consequence, django.contrib.auth.forms.UsernameField is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.",
    "Advisory": {
      "Severity": "Important",
      "Issued": {
        "Date": "2023-11-07"
      },
      "Updated": {
        "Date": "2023-11-08"
      },
      "Cves": [
        {
          "ID": "CVE-2023-36053",
          "CVSS3": "7.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "Impact": "Important",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2023-36053",
          "CWE": "CWE-1333",
          "Public": "20230703"
        },
        {
          "ID": "CVE-2023-41164",
          "CVSS3": "6.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
          "Impact": "Moderate",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2023-41164",
          "CWE": "CWE-400",
          "Public": "20230904"
        },
        {
          "ID": "CVE-2023-43665",
          "CVSS3": "5.3/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
          "Impact": "Moderate",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2023-43665",
          "CWE": "CWE-1333",
          "Public": "20231004"
        },
        {
          "ID": "CVE-2023-46695",
          "CVSS3": "0.0/CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:N",
          "Impact": "None",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2023-46695",
          "CWE": "CWE-20",
          "Public": "20231101"
        }
      ],
      "AffectedCpeList": [
        "cpe:2.3:o:openanolis:anolis_os:23:*:*:*:*:*:*:* "
      ]
    }
  },
  "Criteria": {
    "Operator": "AND",
    "Criterias": [
      {
        "Operator": "OR",
        "Criterias": null,
        "Criterions": [
          {
            "Comment": "python-django is earlier than 0:django-4.2.7-1.an23",
            "TestRef": "oval:cn.openanolis:tst:20230669001"
          },
          {
            "Comment": "python3-django is earlier than 0:django-4.2.7-1.an23",
            "TestRef": "oval:cn.openanolis:tst:20230669002"
          },
          {
            "Comment": "python3-django-bash-completion is earlier than 0:django-bash-completion-4.2.7-1.an23",
            "TestRef": "oval:cn.openanolis:tst:20230669003"
          },
          {
            "Comment": "python3-django-doc is earlier than 0:django-doc-4.2.7-1.an23",
            "TestRef": "oval:cn.openanolis:tst:20230669004"
          }
        ]
      }
    ],
    "Criterions": [
      {
        "Comment": "Anolis OS 23 is installed",
        "TestRef": "oval:cn.openanolis:tst:1"
      }
    ]
  }
}