{
  "ID": "oval:cn.openanolis:def:20220700",
  "Version": "1",
  "Class": "patch",
  "Metadata": {
    "Title": "ANSA-2022:0700: python3 security update (Moderate)",
    "Affected": {
      "Family": "unix",
      "Platform": [
        "Anolis OS 8"
      ]
    },
    "References": [
      {
        "RefID": "ANSA-2022:0700",
        "RefURL": "https://anas.openanolis.cn/errata/detail/ANSA-2022:0700",
        "Source": "ANSA"
      }
    ],
    "Description": "Package updates are available for Anolis 8 that fix the following vulnerabilities:\n\nCVE-2015-20107:\nIn Python (aka CPython) through 3.10.4, the mailcap module does not add escape characters into commands discovered in the system mailcap file. This may allow attackers to inject shell commands into applications that call mailcap.findmatch with untrusted input (if they lack validation of user-provided filenames or arguments).\n\nCVE-2019-16056:\nAn issue was discovered in Python through 2.7.16, 3.x through 3.5.7, 3.6.x through 3.6.9, and 3.7.x through 3.7.4. The email module wrongly parses email addresses that contain multiple @ characters. An application that uses the email module and implements some kind of checks on the From/To headers of a message could be tricked into accepting an email address that should be denied. An attack may be the same as in CVE-2019-11340; however, this CVE applies to Python more generally.\n\nCVE-2019-16935:\nThe documentation XML-RPC server in Python through 2.7.16, 3.x through 3.6.9, and 3.7.x through 3.7.4 has XSS via the server_title field. This occurs in Lib/DocXMLRPCServer.py in Python 2.x, and in Lib/xmlrpc/server.py in Python 3.x. If set_server_title is called with untrusted input, arbitrary JavaScript can be delivered to clients that visit the http URL for this server.\n\nCVE-2019-9636:\nPython 2.7.x through 2.7.16 and 3.x through 3.7.2 is affected by: Improper Handling of Unicode Encoding (with an incorrect netloc) during NFKC normalization. The impact is: Information disclosure (credentials, cookies, etc. that are cached against a given hostname). The components are: urllib.parse.urlsplit, urllib.parse.urlparse. The attack vector is: A specially crafted URL could be incorrectly parsed to locate cookies or authentication data and send that information to a different host than when parsed correctly. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.7, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.3, v3.7.3rc1, v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.\n\nCVE-2019-9740:\nAn issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the query string after a ? character) followed by an HTTP header or a Redis command. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.\n\nCVE-2019-9947:\nAn issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the path component of a URL that lacks a ? character) followed by an HTTP header or a Redis command. This is similar to the CVE-2019-9740 query string issue. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.\n\nCVE-2019-9948:\nurllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.\n\nCVE-2020-27619:\nIn Python 3 through 3.9.0, the Lib/test/multibytecodec_support.py CJK codec tests call eval() on content retrieved via HTTP.\n\nCVE-2020-8492:\nPython 2.7 through 2.7.17, 3.5 through 3.5.9, 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 through 3.8.1 allows an HTTP server to conduct Regular Expression Denial of Service (ReDoS) attacks against a client because of urllib.request.AbstractBasicAuthHandler catastrophic backtracking.\n\nCVE-2021-23336:\nThe package python/cpython from 0 and before 3.6.13, from 3.7.0 and before 3.7.10, from 3.8.0 and before 3.8.8, from 3.9.0 and before 3.9.2 are vulnerable to Web Cache Poisoning via urllib.parse.parse_qsl and urllib.parse.parse_qs by using a vector called parameter cloaking. When the attacker can separate query parameters using a semicolon (;), they can cause a difference in the interpretation of the request between the proxy (running with default configuration) and the server. This can result in malicious requests being cached as completely safe ones, as the proxy would usually not see the semicolon as a separator, and therefore would not include it in a cache key of an unkeyed parameter.\n\nCVE-2021-3177:\nPython 3.x through 3.9.1 has a buffer overflow in PyCArg_repr in _ctypes/callproc.c, which may lead to remote code execution in certain Python applications that accept floating-point numbers as untrusted input, as demonstrated by a 1e300 argument to c_double.from_param. This occurs because sprintf is used unsafely.\n\nCVE-2021-3426:\nThere's a flaw in Python 3's pydoc. A local or adjacent attacker who discovers or is able to convince another local or adjacent user to start a pydoc server could access the server and use it to disclose sensitive information belonging to the other user that they would not normally be able to access. The highest risk of this flaw is to data confidentiality. This flaw affects Python versions before 3.8.9, Python versions before 3.9.3 and Python versions before 3.10.0a7.\n\nCVE-2022-0391:\nA flaw was found in Python, specifically within the urllib.parse module. This module helps break Uniform Resource Locator (URL) strings into components. The issue involves how the urlparse method does not sanitize input and allows characters like '\\r' and '\\n' in the URL path. This flaw allows an attacker to input a crafted URL, leading to injection attacks. This flaw affects Python versions prior to 3.10.0b1, 3.9.5, 3.8.11, 3.7.11 and 3.6.14.",
    "Advisory": {
      "Severity": "Moderate",
      "Issued": {
        "Date": "2022-09-21"
      },
      "Updated": {
        "Date": "2022-11-30"
      },
      "Cves": [
        {
          "ID": "CVE-2015-20107",
          "CVSS3": "7.1/CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:L",
          "Impact": "Important",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2015-20107",
          "CWE": "CWE-20-\u003eCWE-77",
          "Public": "20220921"
        },
        {
          "ID": "CVE-2019-16056",
          "CVSS3": "7.3/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
          "Impact": "Important",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2019-16056",
          "CWE": "CWE-20",
          "Public": "20220921"
        },
        {
          "ID": "CVE-2019-16935",
          "CVSS3": "6.1/CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
          "Impact": "Moderate",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2019-16935",
          "CWE": "CWE-79",
          "Public": "20220921"
        },
        {
          "ID": "CVE-2019-9636",
          "CVSS3": "9.8/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
          "Impact": "Critical",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2019-9636",
          "CWE": "CWE-172",
          "Public": "20220921"
        },
        {
          "ID": "CVE-2019-9740",
          "CVSS3": "6.5/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
          "Impact": "Moderate",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2019-9740",
          "CWE": "CWE-113",
          "Public": "20220921"
        },
        {
          "ID": "CVE-2019-9947",
          "CVSS3": "6.5/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
          "Impact": "Moderate",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2019-9947",
          "CWE": "CWE-113",
          "Public": "20220921"
        },
        {
          "ID": "CVE-2019-9948",
          "CVSS3": "7.4/CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
          "Impact": "Important",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2019-9948",
          "CWE": "CWE-749",
          "Public": "20220921"
        },
        {
          "ID": "CVE-2020-27619",
          "CVSS3": "7.5/CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
          "Impact": "Important",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2020-27619",
          "CWE": "CWE-95",
          "Public": "20201022"
        },
        {
          "ID": "CVE-2020-8492",
          "CVSS3": "6.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
          "Impact": "Moderate",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2020-8492",
          "CWE": "CWE-400",
          "Public": "20220921"
        },
        {
          "ID": "CVE-2021-23336",
          "CVSS3": "5.9/CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:H",
          "Impact": "Moderate",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2021-23336",
          "CWE": "CWE-444",
          "Public": "20220921"
        },
        {
          "ID": "CVE-2021-3177",
          "CVSS3": "5.9/CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "Impact": "Moderate",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2021-3177",
          "CWE": "CWE-120",
          "Public": "20220921"
        },
        {
          "ID": "CVE-2021-3426",
          "CVSS3": "5.7/CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
          "Impact": "Moderate",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2021-3426",
          "CWE": "CWE-200",
          "Public": "20220921"
        },
        {
          "ID": "CVE-2022-0391",
          "CVSS3": "5.3/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
          "Impact": "Moderate",
          "Href": "https://anas.openanolis.cn/cves/detail/CVE-2022-0391",
          "CWE": "CWE-74",
          "Public": "20220921"
        }
      ],
      "AffectedCpeList": [
        "cpe:2.3:o:openanolis:anolis_os:8:*:*:*:*:*:*:* "
      ]
    }
  },
  "Criteria": {
    "Operator": "AND",
    "Criterias": [
      {
        "Operator": "OR",
        "Criterias": null,
        "Criterions": [
          {
            "Comment": "platform-python is earlier than 0:python-3.6.8-47.0.1.an8_6",
            "TestRef": "oval:cn.openanolis:tst:20220700001"
          },
          {
            "Comment": "platform-python-debug is earlier than 0:python-debug-3.6.8-47.0.1.an8_6",
            "TestRef": "oval:cn.openanolis:tst:20220700002"
          },
          {
            "Comment": "platform-python-devel is earlier than 0:python-devel-3.6.8-47.0.1.an8_6",
            "TestRef": "oval:cn.openanolis:tst:20220700003"
          },
          {
            "Comment": "python3-idle is earlier than 0:idle-3.6.8-47.0.1.an8_6",
            "TestRef": "oval:cn.openanolis:tst:20220700004"
          },
          {
            "Comment": "python3-libs is earlier than 0:libs-3.6.8-47.0.1.an8_6",
            "TestRef": "oval:cn.openanolis:tst:20220700005"
          },
          {
            "Comment": "python3-test is earlier than 0:test-3.6.8-47.0.1.an8_6",
            "TestRef": "oval:cn.openanolis:tst:20220700006"
          },
          {
            "Comment": "python3-tkinter is earlier than 0:tkinter-3.6.8-47.0.1.an8_6",
            "TestRef": "oval:cn.openanolis:tst:20220700007"
          },
          {
            "Comment": "python3 is earlier than 0:3.6.8-47.0.1.an8_6",
            "TestRef": "oval:cn.openanolis:tst:20220700008"
          }
        ]
      }
    ],
    "Criterions": [
      {
        "Comment": "Anolis OS 8 is installed",
        "TestRef": "oval:cn.openanolis:tst:1"
      }
    ]
  }
}